name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Set up Node.js and NPM auth
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@bitzonegaming'

      # 3. Install dependencies
      - run: npm ci

      # 4. Generate barrels
      - run: npm run gen:barrels

      # 5. Build (emit JS + d.ts into dist/)
      - run: npm run build

      # 6. Run tests
      - run: npm test

      # 7. Publish to npm (will pack dist/ per your `files` + exports)
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
